version: '3.8'
services:
  backend:
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healtz"]
      interval: 30s
      timeout: 10s
      retries: 5
    build:
      context: ./backend
    ports:
      - "7080:8080"
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env
  frontend:
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healtz"]
      interval: 30s
      timeout: 10s
      retries: 5
    build:
      context: ./frontend
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    ports:
      - "7081:8080"
    env_file:
      - .env
    depends_on:
      - mariadb
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
  mariadb:
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASS}"]
      interval: 30s
      timeout: 10s
      retries: 5
    image: mariadb:latest
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "9306:3306"
    volumes:
      - ./mariadb-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci