version: '3.8'
services:
  backend:
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healtz"]
      interval: 30s
      timeout: 10s
      retries: 5
    build: ./backend
    ports:
      - "9080:8080"
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - ./nginx/ssl:/app/nginx/ssl
      - ./nginx/backend:/app/nginx/backend
  frontend:
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healtz"]
      interval: 30s
      timeout: 10s
      retries: 5
    build:
      context: ./frontend
      args:
        REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
    ports:
      - "9081:8080"
    env_file:
      - .env
    depends_on:
      - mariadb
  mariadb:
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASS}"]
      interval: 30s
      timeout: 10s
      retries: 5
    image: mariadb:latest
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "9306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
  nginx:
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 5
    build: ./nginx
    ports:
      - "9082:80"
      - "9443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/backend:/etc/nginx/backend
volumes:
  mariadb_data:
